(function () {
  "use strict";
  // Demo adapter only. Replace with GET /api/tutors and POST /api/tutor-requests later.
  const tutorData = [
    { id: "t-1", name: "Ananya Rao", subjects: ["Mathematics", "Physics"], grades: [8, 9, 10], bio: "Helps students understand concepts step by step.", experience: "4 years teaching", availability: "Available today", rating: "4.9" },
    { id: "t-2", name: "Rohan Shah", subjects: ["Chemistry", "Biology"], grades: [9, 10, 11, 12], bio: "Makes science feel clearer with visual explanations.", experience: "6 years teaching", availability: "This week", rating: "4.8" },
    { id: "t-3", name: "Maya Iyer", subjects: ["English"], grades: [6, 7, 8, 9, 10], bio: "Supports writing, grammar, reading, and confident answers.", experience: "5 years teaching", availability: "Available now", rating: "4.9" },
    { id: "t-4", name: "Neel Verma", subjects: ["Mathematics", "Physics"], grades: [11, 12], bio: "Calm support for tougher exam concepts and problem solving.", experience: "7 years teaching", availability: "Today", rating: "4.8" },
    { id: "t-5", name: "Sana Khan", subjects: ["Biology", "Chemistry"], grades: [8, 9, 10], bio: "Uses simple examples to connect lessons to real life.", experience: "3 years teaching", availability: "This week", rating: "4.7" }
  ];
  const filters = { search: document.getElementById("tutorSearch"), subject: document.getElementById("tutorSubject"), grade: document.getElementById("tutorGrade"), availability: document.getElementById("tutorAvailability") };
  function escapeHtml(value) { const node = document.createElement("span"); node.textContent = String(value || ""); return node.innerHTML; }
  function initials(name) { return name.split(" ").map((word) => word[0]).join("").slice(0,2); }
  function matches(tutor) { const search = filters.search.value.trim().toLowerCase(); const subject = filters.subject.value; const grade = Number(filters.grade.value || 0); const availability = filters.availability.value; return (!search || tutor.name.toLowerCase().includes(search)) && (!subject || tutor.subjects.includes(subject)) && (!grade || tutor.grades.includes(grade)) && (!availability || tutor.availability === availability || (availability === "Today" && tutor.availability === "Available today")); }
  function render() { const tutors = tutorData.filter(matches); const grid = document.getElementById("tutorGrid"); document.getElementById("tutorResultCount").textContent = `${tutors.length} demo ${tutors.length === 1 ? "tutor" : "tutors"} found`; grid.innerHTML = tutors.length ? tutors.map((tutor) => `<article class="human-tools-card tutor-card"><div class="tutor-card-head"><span class="tutor-card-avatar">${initials(tutor.name)}</span><div><h2>${escapeHtml(tutor.name)}</h2><p>${escapeHtml(tutor.experience)} · ${escapeHtml(tutor.rating)} ★</p></div></div><p class="tutor-card-bio">“${escapeHtml(tutor.bio)}”</p><div class="tutor-tags"><span>${tutor.subjects.join(" · ")}</span><span>Grades ${tutor.grades[0]}–${tutor.grades[tutor.grades.length - 1]}</span></div><p class="tutor-availability">${escapeHtml(tutor.availability)}</p><div class="tutor-card-actions"><button class="human-tools-secondary" type="button" data-tutor-action="profile" data-tutor-id="${tutor.id}">View Profile</button><button class="human-tools-primary" type="button" data-tutor-action="request" data-tutor-id="${tutor.id}">Request Help</button></div></article>`).join("") : '<div class="human-tools-empty"><strong>No tutors match those filters</strong>Try another subject, grade, or availability.</div>'; }
  function openTutorDialog(tutor, mode) { const dialog = document.getElementById("tutorDialog"); const content = document.getElementById("tutorDialogContent"); const isRequest = mode === "request"; content.innerHTML = `<div class="tutor-dialog-head"><div><span class="human-tools-kicker">Demo tutor profile</span><h2 id="tutorDialogTitle" style="margin:10px 0 0">${isRequest ? `Request help from ${escapeHtml(tutor.name)}` : escapeHtml(tutor.name)}</h2></div><button class="tutor-dialog-close" type="button" data-close-dialog aria-label="Close">×</button></div>${isRequest ? `<form id="tutorRequestForm"><div class="doubt-field"><label for="requestSubject">Subject</label><select id="requestSubject">${tutor.subjects.map((subject) => `<option>${subject}</option>`).join("")}</select></div><div class="doubt-field"><label for="requestTopic">What do you need help with?</label><textarea id="requestTopic" required placeholder="Add a short topic or question..."></textarea></div><p id="tutorRequestStatus" class="human-tools-status" hidden role="status"></p><div class="tutor-dialog-actions"><button class="human-tools-secondary" type="button" data-close-dialog>Cancel</button><button class="human-tools-primary" type="submit">Send request</button></div></form>` : `<p class="tutor-card-bio">${escapeHtml(tutor.bio)}</p><div class="tutor-tags"><span>${tutor.subjects.join(" · ")}</span><span>Grades ${tutor.grades.join(", ")}</span><span>${escapeHtml(tutor.experience)}</span><span>${escapeHtml(tutor.rating)} ★ demo rating</span></div><p class="tutor-availability">${escapeHtml(tutor.availability)}</p><div class="tutor-dialog-actions"><button class="human-tools-secondary" type="button" data-close-dialog>Close</button><button class="human-tools-primary" type="button" data-tutor-action="request" data-tutor-id="${tutor.id}">Request Help</button></div>`}`; dialog.showModal(); }
  document.getElementById("tutorFilters").addEventListener("input", render); document.getElementById("clearTutorFilters").addEventListener("click", () => { document.getElementById("tutorFilters").reset(); render(); });
  document.getElementById("tutorGrid").addEventListener("click", (event) => { const button = event.target.closest("[data-tutor-action]"); if (!button) return; const tutor = tutorData.find((item) => item.id === button.dataset.tutorId); if (tutor) openTutorDialog(tutor, button.dataset.tutorAction); });
  document.getElementById("tutorDialog").addEventListener("click", (event) => { if (event.target === event.currentTarget || event.target.closest("[data-close-dialog]")) event.currentTarget.close(); const button = event.target.closest("[data-tutor-action]"); if (button) { const tutor = tutorData.find((item) => item.id === button.dataset.tutorId); if (tutor) openTutorDialog(tutor, button.dataset.tutorAction); } });
  document.getElementById("tutorDialog").addEventListener("submit", (event) => { if (event.target.id !== "tutorRequestForm") return; event.preventDefault(); const message = document.getElementById("requestTopic").value.trim(); const status = document.getElementById("tutorRequestStatus"); if (!message) { status.hidden = false; status.textContent = "Add a short message before sending your request."; return; } status.hidden = false; status.textContent = "Request saved as a demo preview. Tutorly will send it when the tutor-request API is connected."; event.target.reset(); });
  window.TutorlyFindTutor = { tutorData, render };
  render();
})();
